global:
  scrape_interval: 3s # Tempo entre cada coleta de métricas

scrape_configs:
  - job_name: 'orders_service'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'payments_service'
    static_configs:
      - targets: ['host.docker.internal:8001']