# Generated by Django 5.1 on 2024-08-14 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('COMPLETO', 'Completo'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID da Transação'),
        ),
    ]
